#!/usr/bin/env bash
# Install spend as rootless systemd --user units — the fallback deploy path.
#
# `docker compose up -d` is the one to reach for first (see compose.yaml). This is for a
# box with no Docker, and it is the same code against the same directories, so the two are
# interchangeable — but never both at once: each runs an extraction worker, and two of
# those will send the same receipt to `sir` twice.
#
# Generates units from deploy/systemd/*.in into ~/.config/systemd/user/, substituting the
# paths this checkout actually resolved to. Re-running it is the upgrade path: it
# regenerates, reloads, and restarts.
#
# Nothing here needs root, and nothing here touches the LAN. Publishing to the tailnet is
# one command, printed at the end, and left to you because it is an outward-facing change.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="${VENV:-$REPO/.venv}"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
PORT="${SPEND_PORT:-8089}"
SIR="${SPEND_SIR_BASE_URL:-http://127.0.0.1:8000}"

if [ ! -x "$VENV/bin/spend" ]; then
  echo "No venv at $VENV. Run:  uv sync" >&2
  exit 1
fi

mkdir -p "$UNIT_DIR"
for template in "$REPO"/deploy/systemd/*.in; do
  name="$(basename "$template" .in)"
  { echo "# Generated by scripts/service-install.sh from deploy/systemd/$(basename "$template")."
    echo "# Edits here are overwritten on the next install. Change the template instead."
    sed -e "s|@REPO@|$REPO|g" -e "s|@VENV@|$VENV|g" \
        -e "s|@PORT@|$PORT|g" -e "s|@SIR@|$SIR|g" "$template"
  } > "$UNIT_DIR/$name"
  echo "wrote $UNIT_DIR/$name"
done

systemctl --user daemon-reload

# The timers are enabled; the service is not, and that is deliberate. Both timers run while
# the store is locked -- the backup copies ciphertext and needs no key, and the feed pull
# holds only public keys -- so they are safe to start at boot. The web app needs the
# passphrase, so it is started by `spend unlock` and stopped by `spend lock`. A box that
# reboots comes up locked, appending, and not serving.
systemctl --user enable --now spend-backup.timer
systemctl --user enable --now spend-feeds.timer
systemctl --user disable spend.service 2>/dev/null || true

# Survives logout. Without it the units stop when the last session ends, which on a
# headless box means "after you close the ssh you used to install it".
loginctl enable-linger "$USER" 2>/dev/null || \
  echo "note: could not enable linger; the service will stop when your session ends"

echo
systemctl --user --no-pager --lines=0 list-timers 'spend-*' || true
cat <<EOF

Timers are running. The web app is not: it needs your passphrase.

    spend init      once, to make the key   (write the printed backup key on PAPER)
    spend unlock    replays the log and starts the service
    spend lock      stops it and forgets everything decrypted

Nothing under ~/.local/share/spend is readable without that passphrase, including by the
nightly feed pull, which can append what it cannot read.

Running on http://127.0.0.1:$PORT once unlocked — loopback only.

To reach it from the phone, publish it on the tailnet:

    tailscale serve --service=svc:spend --https=443 http://127.0.0.1:$PORT

Then open https://spend.<your-tailnet>.ts.net/ and add it to the home screen.

    systemctl --user status spend      # is it up
    journalctl --user -u spend -f      # what is it doing
    $VENV/bin/spend doctor             # what did it resolve

Backups land in \$HOME/backups/spend nightly. To take one now:

    $VENV/bin/spend backup
EOF
