#!/usr/bin/env bash
# Install spend as rootless systemd --user units.
#
# Generates units from deploy/systemd/*.in into ~/.config/systemd/user/, substituting the
# paths this checkout actually resolved to. Re-running it is the upgrade path: it
# regenerates, reloads, and restarts.
#
# Nothing here needs root, and nothing here touches the LAN. Publishing to the tailnet is
# one command, printed at the end, and left to you because it is an outward-facing change.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="${VENV:-$REPO/.venv}"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
PORT="${SPEND_PORT:-8089}"
SIR="${SPEND_SIR_BASE_URL:-http://127.0.0.1:8000}"

if [ ! -x "$VENV/bin/spend" ]; then
  echo "No venv at $VENV. Run:  uv sync" >&2
  exit 1
fi

mkdir -p "$UNIT_DIR"
for template in "$REPO"/deploy/systemd/*.in; do
  name="$(basename "$template" .in)"
  { echo "# Generated by scripts/service-install.sh from deploy/systemd/$(basename "$template")."
    echo "# Edits here are overwritten on the next install. Change the template instead."
    sed -e "s|@REPO@|$REPO|g" -e "s|@VENV@|$VENV|g" \
        -e "s|@PORT@|$PORT|g" -e "s|@SIR@|$SIR|g" "$template"
  } > "$UNIT_DIR/$name"
  echo "wrote $UNIT_DIR/$name"
done

systemctl --user daemon-reload
systemctl --user enable --now spend.service
systemctl --user enable --now spend-backup.timer

# Survives logout. Without it the units stop when the last session ends, which on a
# headless box means "after you close the ssh you used to install it".
loginctl enable-linger "$USER" 2>/dev/null || \
  echo "note: could not enable linger; the service will stop when your session ends"

echo
systemctl --user --no-pager --lines=0 status spend.service || true
cat <<EOF

Running on http://127.0.0.1:$PORT — loopback only.

To reach it from the phone, publish it on the tailnet:

    tailscale serve --service=svc:spend --https=443 http://127.0.0.1:$PORT

Then open https://spend.<your-tailnet>.ts.net/ and add it to the home screen.

    systemctl --user status spend      # is it up
    journalctl --user -u spend -f      # what is it doing
    $VENV/bin/spend doctor             # what did it resolve
EOF
